language: objective-c

script: 
  - brew install https://raw2.github.com/enricosada/homebrew/984a9711740f75e65306cca045fc43d64c306acc/Library/Formula/fsharp.rb
  - brew doctor fsharp
  - which fsharpi
  - which fsharpc

