language: objective-c

script: 
  - brew install https://raw2.github.com/enricosada/homebrew/cb403d7760cc1e6864fd95766cb1e3ed9b4dbf51/Library/Formula/fsharp.rb
  - brew doctor fsharp
  - which fsharpi
  - which fsharpc

