language: objective-c

env:
  - MONO_VERSION="3.2.6"

install:
  - brew install https://raw.github.com/enricosada/homebrew-binary/mono/mono.rb --verbose

script: 
  - which mono
  - mono --version
  - brew install https://raw.github.com/enricosada/homebrew/93f7611623691fe33199f8fb5b07a2335fc3402b/Library/Formula/fsharp.rb --verbose
  - brew doctor fsharp
  - which fsharpi
  - which fsharpc
  - brew test fsharp

