language: objective-c

install:
  - brew tap enricosada/binary
  - brew install enricosada/binary/mono

script: 
  - which mono
  - mono --version
  - brew install https://raw.github.com/enricosada/homebrew/93f7611623691fe33199f8fb5b07a2335fc3402b/Library/Formula/fsharp.rb --verbose
  - brew doctor fsharp
  - which fsharpi
  - which fsharpc
  - brew test fsharp

