language: objective-c

env:
  - MONO_VERSION="3.2.7" FSHARP_FORMULA="https://raw.github.com/enricosada/homebrew/1fa54f8d6937cad6faee84325b5957ffb933a819/Library/Formula/fsharp.rb"

install:
  - wget "http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script: 
  - which mono
  - mono --version
  - wget "https://github.com/fsharp/fsharp/archive/3.1.1.1.tar.gz"
  - tar xf fsharp-3.1.1.1.tar.gz
  - cd fsharp-3.1.1.1
  - ./autogen.sh --prefix=/Library/Frameworks/Mono.framework/Versions/3.2.7
  - make
  - sudo make install
  - echo brew install ${FSHARP_FORMULA} --verbose --replace-mono-current
  - brew doctor fsharp
  - which fsharpi
  - which fsharpc
  - fsharpi --help
  - fsharpc --help
  - /Library/Frameworks/Mono.framework/Versions/Current/bin/fsharpc --help
  - /Library/Frameworks/Mono.framework/Versions/Current/bin/fsharpi --help

